# Generated by Django 6.0.4 on 2026-04-30 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TalentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('city', models.CharField(max_length=100)),
                ('price_from', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profile_image', models.URLField(blank=True, null=True)),
                ('rating', models.FloatField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='talent.category')),
            ],
        ),
    ]
